services:
  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  css:
    build:
      context: .
      target: development
    volumes:
      - .:/rails
    command: yarn watch:css

  sidekiq:
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: postgres://postgres:postgres@db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: bundle exec sidekiq -C config/sidekiq.yml

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
